---
- name: install start and enable httpd
  hosts: rocky ubuntu
  tasks:
  - name: install package
    package:
      name: httpd
      state: latest
  - name: start and enable service
    service:
      name: httpd
      state: started
      enabled: yes
