---
- name: create user {{ user }}
  vars:
    user: linda
  hosts: drqansible2
  tasks:
  - name: checkuser
    command: id {{ user }}
    register: iduser
  - name:
    debug:
      var: iduser
  - name: before check
    fail:
      msg: user already exists
    when: iduser.rc == 0
  - name: create user {{ user }}
    command: useradd {{ user }}

- name: continuing
  hosts: drqansible2
  tasks:
  - debug:
      msg: we made it
