---
- name: secure sudo
  hosts: all
  tasks:
  - name: remove insecure /etc/sudoers.d/ansible file
    file:
      name: /etc/sudoers.d/ansible
      state: absent
  - name: install new and secure file
    copy:
      content: 'ansible ALL=(ALL) ALL'
      dest: /etc/sudoers.d/ansible
  - name: tuning up /etc/sudoers
    lineinfile:
      line: 'Defaults timestamp_type=global,timestamp_timeout=120,!requiretty'
      name: /etc/sudoers
      validate: /usr/sbin/visudo -cf %s
